version: "3"

services:
    backend-service:
        build: ./backend
        ports:
            - 3000:3000
    frontend-service:
        build: ./frontend
        ports:
            - 8080:8080
        depends_on:
            - backend-service
